""" This module contains the qualification bias arrays. """

TITLE_BIAS = [
    ["SENIOR VICE PRESIDENT", "SVP", "VICE PRESIDENT", "VP", "PRESIDENT", "CHIEF", "DIRECTOR", "HEAD", "LEAD"],
    ["SENIOR MANAGER", "MANAGER", "COORDINATOR", "BUSINESS PARTNER"],
    ["ANALYST", "GENERALIST", "ASSISTANT", "SPECIALIST"],
]

FUNCTION_BIAS = ["TALENT", "RECRUIT", "HIRING", "HUMAN RESOURCES", "HR"]
